name: "Prepare release"

on:
  push:
    tags:
      - "release-*"
  workflow_dispatch:
    # allows manual trigger

permissions:
  contents: "write"

jobs:
  release-all:
    name: "Release all"
    if: ${{ !cancelled() }}
    uses: "./.github/workflows/dotnet.yml"

  release-prep:
    needs: ["release-all"]
    runs-on: "windows-2022"

    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v4
        with:
          path: "Out"
          pattern: "R6Downloader.CLI.*"
          merge-multiple: true

      - name: "Upload win-x64"
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: "R6Downloader.CLI.win-x64"
          path: "Out/R6Downloader.CLI.win-x64"
          if-no-files-found: "error"
          compression-level: 0
          retention-days: 7
          
      - name: "Upload framework"
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: "R6Downloader.CLI.framework"
          path: "Out/R6Downloader.CLI.framework"
          if-no-files-found: "error"
          compression-level: 0
          retention-days: 7